name: M2
channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel=6.29.2
  - ipython=8.21.0
  - numpy=1.26.4
  - tqdm=4.66.2
  - matplotlib
  - scipy
  - torchmetrics
  - pre-commit
  - torch-fidelity
  - pip
  - pip:
    - accelerate==0.27.2
    - torch==2.2.0
    - torchvision==0.17.0
    - kornia

  

